# Generated by Django 3.0.4 on 2020-04-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersprice',
            name='customer_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
