# Generated by Django 3.0.4 on 2020-04-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200404_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersprice',
            name='customer_id',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
